In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Veriler.csv')

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
le = LabelEncoder()
df['cinsiyet'] = le.fit_transform(df['cinsiyet'])
df = df.drop(columns='ulke',axis=1)
df = df.dropna()
df

boy  kilo   yas  cinsiyet
0   130    30  10.0         0
1   125    36  11.0         0
2   135    34  10.0         1
3   133    30   9.0         1
4   129    38  12.0         0
5   180    90  30.0         0
6   190    80  25.0         0
7   175    90  35.0         0
8   177    60  22.0         1
9   185   105  33.0         0
10  165    55  27.0         1
11  155    50  44.0         1
13  162    59  41.0         1
14  167    62  55.0         1
15  174    70  47.0         0
17  187    80  27.0         0
18  183    88  28.0         0
19  159    40  29.0         1
20  164    66  32.0         1
21  166    56  42.0         1

In [5]:
x = df.drop(columns='cinsiyet',axis=1).values
y = df['cinsiyet'].values

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,random_state=0,test_size=0.33)

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
logr = LogisticRegression(random_state = 0)
logr.fit(xtrain,ytrain)

LogisticRegression(random_state=0)

In [12]:
ypred = logr.predict(xtest)
print(ypred)
print(ytest)

[0 1 1 0 0 1 0]
[1 0 1 1 1 1 0]


In [13]:
from sklearn.metrics import confusion_matrix

In [14]:
cm = confusion_matrix(ypred,ytest)
print(cm)

[[1 3]
 [1 2]]
