## Gerekli Kütüphaneler 

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

## Veri Setinin Eklenmesi

In [2]:
df = pd.read_csv('iris.csv')
df = df.dropna()
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    object 
dtypes: float64(4), object(1)
memory usage: 5.9+ KB
None


5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

## Veri Ön İşleme

In [3]:
x = df.iloc[:,0:4].values
y = df.iloc[:,4].values

In [4]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,random_state=0,test_size=0.33)

## Sınıflandırma Modelleri Ve Değerlendirme

In [5]:
from sklearn.metrics import confusion_matrix

In [6]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion='entropy')
dtc.fit(xtrain,ytrain)
dtcPredict = dtc.predict(xtest)
cm = confusion_matrix(ytest,dtcPredict)
print('Decision Tree Classifier')
print(cm)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1,metric='minkowski')
knn.fit(xtrain,ytrain)
knnPredict = knn.predict(xtest)
cm = confusion_matrix(ytest,knnPredict)
print('K Neighbors Classifier')
print(cm)

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10, criterion='entropy')
rfc.fit(xtrain,ytrain)
rfcPredict = rfc.predict(xtest)
cm = confusion_matrix(ytest,rfcPredict)
print('Random Forest Classifier')
print(cm)

from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(xtrain,ytrain)
svcPredict = svc.predict(xtest)
cm = confusion_matrix(ytest,svcPredict)
print('Support Vector Classifier')
print(cm)

Decision Tree Classifier
[[16  0  0]
 [ 0 18  1]
 [ 0  4 11]]
K Neighbors Classifier
[[16  0  0]
 [ 0 17  2]
 [ 0  3 12]]
Random Forest Classifier
[[16  0  0]
 [ 0 18  1]
 [ 0  4 11]]
Support Vector Classifier
[[16  0  0]
 [ 0 18  1]
 [ 0  3 12]]
